import { Freelancer } from './types';
import {
  AdminOverviewStats,
  AdminFreelancerPerformance,
  AdminLeadWithDetails,
  AdminSaleWithDetails,
  AdminMeetingWithDetails,
} from './admin-queries';

export const DEMO_FREELANCERS: Freelancer[] = [
  {
    id: 'fl-101',
    user_id: 'usr-101',
    name: 'Sarah Connor',
    email: 'sarah@trelio.crm',
    phone: '+1 (555) 234-5678',
    country: 'United States',
    timezone: 'America/New_York',
    status: 'active',
    commission_rate: 15.0,
    is_admin: true,
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'fl-102',
    user_id: 'usr-102',
    name: 'David Miller',
    email: 'david.m@trelio.crm',
    phone: '+1 (555) 345-6789',
    country: 'Canada',
    timezone: 'America/Toronto',
    status: 'active',
    commission_rate: 18.0,
    is_admin: false,
    created_at: '2026-08-15T12:00:00Z',
  },
  {
    id: 'fl-103',
    user_id: 'usr-103',
    name: 'Elena Rostova',
    email: 'elena@trelio.crm',
    phone: '+44 20 7946 0912',
    country: 'United Kingdom',
    timezone: 'Europe/London',
    status: 'active',
    commission_rate: 20.0,
    is_admin: false,
    created_at: '2026-09-01T08:30:00Z',
  },
  {
    id: 'fl-104',
    user_id: 'usr-104',
    name: 'Marcus Vance',
    email: 'marcus@trelio.crm',
    phone: '+1 (555) 876-5432',
    country: 'United States',
    timezone: 'America/Los_Angeles',
    status: 'inactive',
    commission_rate: 12.0,
    is_admin: false,
    created_at: '2026-07-20T14:15:00Z',
  },
];

export const DEMO_ADMIN_STATS: AdminOverviewStats = {
  totalLeads: 64,
  callsThisWeek: 118,
  meetingsBooked: 19,
  salesClosedThisMonth: 8,
  commissionOwedThisMonth: 1875.5,
};

export const DEMO_ADMIN_PERFORMANCE: AdminFreelancerPerformance[] = [
  {
    freelancer: DEMO_FREELANCERS[0],
    leadsAssigned: 24,
    callsThisWeek: 45,
    meetingsBooked: 8,
    salesClosed: 4,
    commissionOwed: 950.0,
  },
  {
    freelancer: DEMO_FREELANCERS[1],
    leadsAssigned: 20,
    callsThisWeek: 38,
    meetingsBooked: 6,
    salesClosed: 3,
    commissionOwed: 625.5,
  },
  {
    freelancer: DEMO_FREELANCERS[2],
    leadsAssigned: 15,
    callsThisWeek: 32,
    meetingsBooked: 5,
    salesClosed: 1,
    commissionOwed: 300.0,
  },
  {
    freelancer: DEMO_FREELANCERS[3],
    leadsAssigned: 5,
    callsThisWeek: 3,
    meetingsBooked: 0,
    salesClosed: 0,
    commissionOwed: 0.0,
  },
];

export const DEMO_ADMIN_LEADS: AdminLeadWithDetails[] = [
  {
    id: 'lead-1',
    business_name: 'Apex Plumbing & Heating',
    phone: '+1 (555) 019-2834',
    email: 'info@apexplumbing.com',
    address: '102 Industrial Pkwy',
    city: 'Austin',
    state: 'TX',
    category: 'Plumbing',
    status: 'interested',
    assigned_to: 'fl-101',
    freelancerName: 'Sarah Connor',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    last_call_date: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 'lead-2',
    business_name: 'BrightSpark Electrical Co.',
    phone: '+1 (555) 834-9201',
    email: 'service@brightsparkelectric.com',
    address: '44 Elm Street',
    city: 'Dallas',
    state: 'TX',
    category: 'Electrical',
    status: 'meeting_booked',
    assigned_to: 'fl-101',
    freelancerName: 'Sarah Connor',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    last_call_date: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: 'lead-3',
    business_name: 'Vanguard Roofing Solutions',
    phone: '+1 (555) 438-1192',
    email: 'contact@vanguardroofing.com',
    address: '780 Summit Way',
    city: 'Houston',
    state: 'TX',
    category: 'Roofing',
    status: 'new',
    assigned_to: 'fl-102',
    freelancerName: 'David Miller',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    last_call_date: null,
  },
  {
    id: 'lead-4',
    business_name: 'GreenValley HVAC Specialists',
    phone: '+1 (555) 772-4091',
    email: 'sales@greenvalleyhvac.com',
    address: '1240 Pinecrest Dr',
    city: 'Denver',
    state: 'CO',
    category: 'HVAC',
    status: 'sold',
    assigned_to: 'fl-102',
    freelancerName: 'David Miller',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    last_call_date: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
  {
    id: 'lead-5',
    business_name: 'Pinnacle Tree Care & Removal',
    phone: '+1 (555) 902-3312',
    email: 'support@pinnacletree.com',
    address: '91 Oakridge Ln',
    city: 'Boulder',
    state: 'CO',
    category: 'Landscaping',
    status: 'contacted',
    assigned_to: 'fl-103',
    freelancerName: 'Elena Rostova',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    last_call_date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'lead-6',
    business_name: 'Metro Glass & Window Repair',
    phone: '+1 (555) 231-9984',
    email: 'quotes@metroglass.com',
    address: '300 Commerce Blvd',
    city: 'Phoenix',
    state: 'AZ',
    category: 'Contractor',
    status: 'not_interested',
    assigned_to: 'fl-103',
    freelancerName: 'Elena Rostova',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    last_call_date: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
];

export const DEMO_ADMIN_SALES: AdminSaleWithDetails[] = [
  {
    id: 'sale-1',
    lead_id: 'lead-4',
    freelancer_id: 'fl-101',
    meeting_id: 'meet-1',
    businessName: 'GreenValley HVAC Specialists',
    freelancerName: 'Sarah Connor',
    sale_amount: 1500.0,
    commission_amount: 225.0,
    payment_status: 'confirmed',
    payment_link: 'https://buy.stripe.com/demo1',
    payment_screenshot_url: null,
    credentials_sent: true,
    sold_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 'sale-2',
    lead_id: 'lead-1',
    freelancer_id: 'fl-101',
    meeting_id: 'meet-2',
    businessName: 'Apex Plumbing & Heating',
    freelancerName: 'Sarah Connor',
    sale_amount: 2500.0,
    commission_amount: 375.0,
    payment_status: 'pending',
    payment_link: 'https://buy.stripe.com/demo2',
    payment_screenshot_url: null,
    credentials_sent: false,
    sold_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 'sale-3',
    lead_id: 'lead-2',
    freelancer_id: 'fl-102',
    meeting_id: 'meet-3',
    businessName: 'BrightSpark Electrical Co.',
    freelancerName: 'David Miller',
    sale_amount: 1800.0,
    commission_amount: 324.0,
    payment_status: 'confirmed',
    payment_link: 'https://buy.stripe.com/demo3',
    payment_screenshot_url: null,
    credentials_sent: true,
    sold_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
];

export const DEMO_ADMIN_MEETINGS: AdminMeetingWithDetails[] = [
  {
    id: 'meet-1',
    lead_id: 'lead-1',
    freelancer_id: 'fl-101',
    freelancerName: 'Sarah Connor',
    meeting_datetime: new Date(new Date().setHours(10, 30, 0, 0)).toISOString(),
    lead_timezone: 'America/Chicago',
    platform: 'google_meet',
    meeting_link: 'https://meet.google.com/demo-sarah',
    status: 'scheduled',
    outcome_notes: 'Discuss website redesign, hosting plan, and lead capture form.',
    created_at: new Date().toISOString(),
    lead: {
      business_name: 'Apex Plumbing & Heating',
      phone: '+1 (555) 019-2834',
    },
  },
  {
    id: 'meet-2',
    lead_id: 'lead-3',
    freelancer_id: 'fl-102',
    freelancerName: 'David Miller',
    meeting_datetime: new Date(new Date().getTime() + 1000 * 60 * 60 * 26).toISOString(),
    lead_timezone: 'America/New_York',
    platform: 'zoom',
    meeting_link: 'https://zoom.us/j/demo-david',
    status: 'scheduled',
    outcome_notes: 'Demo contractor portfolio template and SEO service breakdown.',
    created_at: new Date().toISOString(),
    lead: {
      business_name: 'Vanguard Roofing Solutions',
      phone: '+1 (555) 438-1192',
    },
  },
  {
    id: 'meet-3',
    lead_id: 'lead-5',
    freelancer_id: 'fl-103',
    freelancerName: 'Elena Rostova',
    meeting_datetime: new Date(new Date().getTime() + 1000 * 60 * 60 * 48).toISOString(),
    lead_timezone: 'Europe/London',
    platform: 'google_meet',
    meeting_link: 'https://meet.google.com/demo-elena',
    status: 'scheduled',
    outcome_notes: 'UK trades website walkthrough.',
    created_at: new Date().toISOString(),
    lead: {
      business_name: 'Pinnacle Tree Care & Removal',
      phone: '+1 (555) 902-3312',
    },
  },
];
